@VaultEdge.Api_HostAddress = https://localhost:7298

DELETE {{VaultEdge.Api_HostAddress}}/api/accounts/7C0B2C1F-93E8-4159-9038-DC90FBC95D6D
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYmE4YTAwOS1lZTdmLTRjMTItYWU4NS0zMTdkM2I4MTllMzciLCJnaXZlbl9uYW1lIjoiQ2hhbnRhbCIsImZhbWlseV9uYW1lIjoiTGFkdXJuZXIiLCJqdGkiOiI4M2Q0OThkNy04YzM4LTQzMDItODk0Yy04ZmYyYmIxMGJlMTYiLCJleHAiOjE3NzA3NTgyMDgsImlzcyI6IlZhdWx0RWRnZSIsImF1ZCI6IlZhdWx0RWRnZVVzZXJzIn0.UDUgkGNVCdRS-e5KwKMGKe0l2Xiax6K3vDE5UtrsAkA

