@VaultEdge.Api_HostAddress = https://localhost:7298

GET {{VaultEdge.Api_HostAddress}}/api/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYmE4YTAwOS1lZTdmLTRjMTItYWU4NS0zMTdkM2I4MTllMzciLCJnaXZlbl9uYW1lIjoiQ2hhbnRhbCIsImZhbWlseV9uYW1lIjoiTGFkdXJuZXIiLCJqdGkiOiI1MTU5YzcwYS1jMTM5LTQ4OGItYWZmZS1lODU2MTNiYTI4YTkiLCJleHAiOjE3NzA3NTc4ODIsImlzcyI6IlZhdWx0RWRnZSIsImF1ZCI6IlZhdWx0RWRnZVVzZXJzIn0.KQJcUEpZMA3PgVu90Spm1KfwFpoY1_sIpcLqhityLIY
