@VaultEdge.Api_HostAddress = https://localhost:7298

POST {{VaultEdge.Api_HostAddress}}/api/auth/signup/
Content-Type: application/json

{
  "firstName": "Chantal",
  "lastName": "Ladurner",
  "password": "SecrectnumPass32.",
  "dateOfBirth": "2000-01-05T19:21:28.856Z",
  "taxId": "SIMLD123212",
  "identificationId": "ID55FW253",
  "nationality": "IT",
  "email": "chantalladurner@gmail.com",
  "phoneNumber": "2223334444",
  "address": "Rome Str. 1, Rome"
}

###