@VaultEdge.Api_HostAddress = http://localhost:5230

POST {{VaultEdge.Api_HostAddress}}/api/users/
Content-Type: application/json

{
  "firstName": "Ivan",
  "lastName": "Smith",
  "dateOfBirth": "1992-04-15",
  "taxId": "TX12345",
  "identificationId": "ID12345",
  "nationality": "USA",
  "email": "ivan.smith@example.com",
  "phoneNumber": "+12025550123",
  "address": "123 Main St, Springfield"
}

###

GET {{VaultEdge.Api_HostAddress}}/api/users

###

GET {{VaultEdge.Api_HostAddress}}/api/users/55967870-3f95-4b04-a9e5-e401d0e878ab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTk2Nzg3MC0zZjk1LTRiMDQtYTllNS1lNDAxZDBlODc4YWIiLCJlbWFpbCI6Iml2YW4uc21pdGhAZXhhbXBsZS5jb20iLCJleHAiOjE3NjQ1MzAwNTcsImlzcyI6IlZhdWx0RWRnZSIsImF1ZCI6IlZhdWx0RWRnZVVzZXJzIn0.fyv4k6-A6MInx4fNau9lnQRWBWy4DfZ4_AezxfCtTl4

###

DELETE {{VaultEdge.Api_HostAddress}}/api/users/55967870-3f95-4b04-a9e5-e401d0e878ab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTk2Nzg3MC0zZjk1LTRiMDQtYTllNS1lNDAxZDBlODc4YWIiLCJlbWFpbCI6Iml2YW4uc21pdGhAZXhhbXBsZS5jb20iLCJleHAiOjE3NjQ1MzAwNTcsImlzcyI6IlZhdWx0RWRnZSIsImF1ZCI6IlZhdWx0RWRnZVVzZXJzIn0.fyv4k6-A6MInx4fNau9lnQRWBWy4DfZ4_AezxfCtTl4

###

POST {{VaultEdge.Api_HostAddress}}/api/accounts/
Content-Type: application/json

{
  "userId": "1f9e9564-8ce3-4864-8544-1643e71579a3",
  "balance": 23.12,
  "accountType": 0,
  "accountNumber": "stringg"
}

###

GET {{VaultEdge.Api_HostAddress}}/api/accounts

###

DELETE {{VaultEdge.Api_HostAddress}}/api/accounts/55967870-3f95-4b04-a9e5-e401d0e878ab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTk2Nzg3MC0zZjk1LTRiMDQtYTllNS1lNDAxZDBlODc4YWIiLCJlbWFpbCI6Iml2YW4uc21pdGhAZXhhbXBsZS5jb20iLCJleHAiOjE3NjQ1MzAwNTcsImlzcyI6IlZhdWx0RWRnZSIsImF1ZCI6IlZhdWx0RWRnZVVzZXJzIn0.fyv4k6-A6MInx4fNau9lnQRWBWy4DfZ4_AezxfCtTl4

###

GET {{VaultEdge.Api_HostAddress}}/api/users/login/
{
  "email": "ivan.smith@example.com"
}

###