@VaultEdge.Api_HostAddress = http://localhost:5230

POST {{VaultEdge.Api_HostAddress}}/api/users/
Content-Type: application/json

{
  "firstName": "Chantal",
  "lastName": "Ladurner",
  "passwordHash": "PasswordHash12324",
  "dateOfBirth": "2000-01-05T19:21:28.856Z",
  "taxId": "CHLD123212",
  "identificationId": "ID35FW333",
  "nationality": "IT",
  "email": "chantalladurner@gmail.com",
  "phoneNumber": "2223334444",
  "address": "Rome Str. 1, Rome"
}

###

GET {{VaultEdge.Api_HostAddress}}/api/users

###

GET {{VaultEdge.Api_HostAddress}}/api/users/55967870-3f95-4b04-a9e5-e401d0e878ab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTk2Nzg3MC0zZjk1LTRiMDQtYTllNS1lNDAxZDBlODc4YWIiLCJlbWFpbCI6Iml2YW4uc21pdGhAZXhhbXBsZS5jb20iLCJleHAiOjE3NjQ1MzAwNTcsImlzcyI6IlZhdWx0RWRnZSIsImF1ZCI6IlZhdWx0RWRnZVVzZXJzIn0.fyv4k6-A6MInx4fNau9lnQRWBWy4DfZ4_AezxfCtTl4

###

DELETE {{VaultEdge.Api_HostAddress}}/api/users/55967870-3f95-4b04-a9e5-e401d0e878ab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTk2Nzg3MC0zZjk1LTRiMDQtYTllNS1lNDAxZDBlODc4YWIiLCJlbWFpbCI6Iml2YW4uc21pdGhAZXhhbXBsZS5jb20iLCJleHAiOjE3NjQ1MzAwNTcsImlzcyI6IlZhdWx0RWRnZSIsImF1ZCI6IlZhdWx0RWRnZVVzZXJzIn0.fyv4k6-A6MInx4fNau9lnQRWBWy4DfZ4_AezxfCtTl4

###

POST {{VaultEdge.Api_HostAddress}}/api/accounts/
Content-Type: application/json

{
  "userId": "1f9e9564-8ce3-4864-8544-1643e71579a3",
  "balance": 23.12,
  "accountType": 0,
  "accountNumber": "stringg"
}

###

GET {{VaultEdge.Api_HostAddress}}/api/accounts

###

DELETE {{VaultEdge.Api_HostAddress}}/api/accounts/55967870-3f95-4b04-a9e5-e401d0e878ab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTk2Nzg3MC0zZjk1LTRiMDQtYTllNS1lNDAxZDBlODc4YWIiLCJlbWFpbCI6Iml2YW4uc21pdGhAZXhhbXBsZS5jb20iLCJleHAiOjE3NjQ1MzAwNTcsImlzcyI6IlZhdWx0RWRnZSIsImF1ZCI6IlZhdWx0RWRnZVVzZXJzIn0.fyv4k6-A6MInx4fNau9lnQRWBWy4DfZ4_AezxfCtTl4

###

GET {{VaultEdge.Api_HostAddress}}/api/users/login/
{
  "email": "ivan.smith@example.com"
}

###

POST {{VaultEdge.Api_HostAddress}}/api/auth/signup/
Content-Type: application/json

{
  "firstName": "Chantal",
  "lastName": "Ladurner",
  "passwordHash": "PasswordHash12324",
  "dateOfBirth": "2000-01-05T19:21:28.856Z",
  "taxId": "CHLD123212",
  "identificationId": "ID35FW333",
  "nationality": "IT",
  "email": "chantalladurner@gmail.com",
  "phoneNumber": "2223334444",
  "address": "Rome Str. 1, Rome"
}

###

POST {{VaultEdge.Api_HostAddress}}/api/auth/signin/
Content-Type: application/json

{
  "email": "chantalladurner@gmail.com",
  "password": "PasswordHash12324"
}

###