@VaultEdge.Api_HostAddress = http://localhost:5230

POST {{VaultEdge.Api_HostAddress}}/api/users/
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Smith",
  "dateOfBirth": "1992-04-15",
  "taxId": "TX12345",
  "identificationId": "ID12345",
  "nationality": "USA",
  "email": "alice.smith@example.com",
  "phoneNumber": "+12025550123",
  "address": "123 Main St, Springfield"
}

###

GET {{VaultEdge.Api_HostAddress}}/api/users

###

GET {{VaultEdge.Api_HostAddress}}/api/users/0c5c0a0a-cdff-4cc5-a978-e895baecdfaa

###

POST {{VaultEdge.Api_HostAddress}}/api/accounts/
Content-Type: application/json

{
  "userId": "1f9e9564-8ce3-4864-8544-1643e71579a3",
  "balance": 23.12,
  "accountType": 0,
  "accountNumber": "stringg"
}

###

GET {{VaultEdge.Api_HostAddress}}/api/accounts

###