@VaultEdge.Api_HostAddress = https://localhost:7298
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZjE1N2M1Yy05ZDFhLTRlNzYtODNmMS1mOWZkZWFlY2VlYmYiLCJnaXZlbl9uYW1lIjoiQ2hhbnRhbCIsImZhbWlseV9uYW1lIjoiTGFkdXJuZXIiLCJqdGkiOiI2MjNjNzMyNC01ODMyLTQ5ZGItYjYxNS0yYWFkYzI5OTEzM2QiLCJlbWFpbCI6ImNoYW50YWxsYWR1cm5lckBnbWFpbC5jb20iLCJzZWN1cml0eVN0YW1wIjoiQkFSNVJUVFVDNEo2NkpVWFRER1RLWUwyUERYSzVCWk4iLCJleHAiOjE3NzE3Nzk4NTgsImlzcyI6IlZhdWx0RWRnZSIsImF1ZCI6IlZhdWx0RWRnZVVzZXJzIn0.rnJhKY_MRRgZg0f0I5D7EnOpy4FXAOkfKkJMj8Oy-uU

GET {{VaultEdge.Api_HostAddress}}/api/customer
Authorization: Bearer {{token}}

###